### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by rposn** [StatisticalServicesCentre/ClimateObject#15]
I would need to know the date format of the "data" to improve the "timeseries" graphical method. 
I know it is given as input argument at the beginning, for example:
climObj <- climate(data_tables=list(data6),date_formats=list("%Y-%m-%d"))
But I do not know where the "date_formats" argument is saved. Is it stored somewhere in the climate object?
Thank you in advance and best regards

**Comment by volloholic** [comment]
What exactly are you wanting to do? The date is stored as a R date so any format required can be obtained irrespective of the format it is stored in, using inbuilt r functions. Lubridate is one of the packages used to improve this functionality and already required by the object.

**Comment by rposn** [comment]
This is to improve the performance of the timeseries plot. In order to have an appropriate timeseries, it is necessary to work with "dates" as "date class" (as.Date) instead of as "character class". If the date format is not a default format recognised by R ("%Y-%m-%d" or "%Y/%m/%d") then it will be difficult to manage the dates, for instance, to place the the "xtick" labels.
If the date format is saved in the climate Object in the same way as the name of the variables, it should be easy to retrieve it from the object.

Besides that, and following your comments, I tried to run the get_climate_data_objects(data_list) to obtain the "climate_data_objs" without "time period" information (which means an empty data_list). In this way, the method should not care about the time period. However, I get the following error (see also image attached):
Error in climate_data_objs <- get_climate_data_objects(data_list) : 
  Specify the time period the data needs to be in

![error_time_period](https://cloud.githubusercontent.com/assets/12081199/7724876/b622de36-fef5-11e4-8b03-63febeb5b7e2.PNG)

Is there a way to specify that I do not want to use a "time_label"?

**Comment by volloholic** [comment]
However the date is passed in it should be stored as.Date have you had a problem with the date field not being stored as.Date? If so that is a bug and I should fix it, please send me the data and I'll look into it.

The error when not specifying a time period is deliberate. This is because the system is set up to convert data between levels where possible. If no time label is specified you could get data from different time levels mixed up. However you are absolutely right that we should be writing functions that can give something sensible whenever the time period is sensible.for that function. What is not clear to me is exactly what should be happening when there are data of multiple time_periods

For example my understanding is that for your functions you may well be interested in different time labels but the graphs should probably be treated differently in each case? I could set up an time label for all available but we need to decide what we want it to return in all cases. What would you want to happen if you had a climate object with Daily, monthly and Yearly data? Should this depend on what is original data and what is calculated(data can be summerised to different time periods or mergedinto a combined data frame these are stored as separate calculated data)?

**Comment by rposn** [comment]
You are right, the "date" is actually saved as.Date, I did not notice that before. This makes not necessary to work with the "date_format".
This works fine for daily data, but for subdaily data we might have problems, because the Date class ignores the time, so that if the user wants to plot hourly values within one day (i.e. subdaily values), all the data will be plotted at the same "xtick" (they will be plotted in the xtick of that day).
To avoid this it could be better to save the date as "POSIXct" object for subdaily data. This object keeps the information of the time. (see for example: http://www.noamross.net/blog/2014/2/10/using-times-and-dates-in-r---presentation-code.html) 
I think we need to save the date/time information in different classes depending on whether it is "daily", "subdaily", "yearly" and "subyearly".
For the timeseries plot I can take advantage of the command "difftime" to obtain the time sequence required for the plot. The command retrieves the time interval between one observation and the next one.
@volloholic re "What would you want to happen if you had a climate object with Daily, monthly and Yearly data?" I guess that there will be one "data_obj" for each kind of data. I think that daily data should not be saved in the same data.frame as monthly data. If there is one "data_obj" for each time period (one for daily, one for monthly, etc.) within one climate object, the plots should work fine.

**Comment by volloholic** [comment]
For subdaily there is a date_time_label we had long discussions about whether we should store date time together in Date that was my original desire but we ran into artificial problems due to (admittedly rare) changes in time zones which led to some valid data being considered missing (1 day in the 1960 in a Kenyan example) the decision was to use a date time column for subdaily data where we use an appropriate date time definition as you suggested.
For the multiple data objects you are correct that a given data object would only have data at one time period and this is stored as metadata. Any given data can be merged or summarised and it would then appear in two data objects, giving rise to the complication, do you just want the original yearly data or all the yearly data. What we need to think is what is appropriate data to return in all cases, I'll be back to good internet tomorrow shall we have a call to sort it out properly?

**Comment by rposn** [comment]
Yes, we can have a call tomorrow. If you want we can use the tool we used last time, so that anyone else can join us. When would it be a good time for you?

**Comment by volloholic** [comment]
I believe this issue is now adressed
